version: 2

project_name: pomo

before:
  hooks:
    - go mod tidy
    - go vet ./...
    - go test ./...

builds:
  - id: pomo
    binary: pomo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - android
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
      - goos: android
        goarch: amd64
      - goos: android
        goarch: arm
    ldflags:
      - -s -w -X github.com/Bahaaio/pomo/cmd.version={{.Version}}

  - id: pomo-android-arm
    binary: pomo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "7"
    ldflags:
      - -s -w -X github.com/Bahaaio/pomo/cmd.version={{.Version}}

changelog:
  sort: asc
  use: github
  format: "{{ .SHA }}: {{ .Message }}{{ with .AuthorUsername }} (@{{ . }}){{ end }}"
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "^refactor:"
      - "^style:"
  groups:
    - title: 💥 Breaking Changes
      regexp: '^.*?(\w+(\([[:word:]]+\))?!:).+$'
      order: 0
    - title: 🚀 Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 🐛 Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 🧹 Others
      order: 999

archives:
  - id: default
    ids:
      - pomo
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm" }}armv{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE
      - pomo.yaml

  - id: android-arm
    ids:
      - pomo-android-arm
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_Android_armv7
    files:
      - README.md
      - LICENSE
      - pomo.yaml

homebrew_casks:
  - name: pomo
    repository:
      owner: Bahaaio
      name: homebrew-pomo
    homepage: https://github.com/Bahaaio/pomo
    description: A timer-first Pomodoro TUI with persistent task context.
    license: MIT
    skip_upload: "true"

    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pomo"]
          end

nfpms:
  - id: default
    ids:
      - pomo
    maintainer: Bahaa Mohamed <bahaa-dev@proton.me>
    description: A timer-first Pomodoro TUI with persistent task context.
    homepage: https://github.com/Bahaaio/pomo
    license: MIT
    formats:
      - deb
      - rpm

release:
  github:
    owner: Bahaaio
    name: pomo
  name_template: "v{{.Version}}"
  footer: |
    ## Install

    ### Go
    ```bash
    go install github.com/Bahaaio/pomo@latest
    ```

    ### Download Binary
    Download from the assets below for your platform.

    ---
